import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

// components
import {useMetaMask, MetaMaskProvider} from '../state/useMetaMask'

const TestComponent = () => {

  const {connect, account} = useMetaMask();

  const onButtonClick = () => connect();

  return (
    <div>
      {account ? account : <button onClick={onButtonClick}>test</button>}
    </div>
  )
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MetaMaskProvider>
        <TestComponent />
      </MetaMaskProvider>
    </div>
  )
}

export default Home
